//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veb_portal_za_aukcijsku_prodaju.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public Korisnik()
        {
            this.Aukcijas = new HashSet<Aukcija>();
            this.Bids = new HashSet<Bid>();
            this.Narudzbinas = new HashSet<Narudzbina>();
        }
    
        public int KorisnikID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Lozinka { get; set; }
        public string Email { get; set; }
        public Nullable<int> BrojTokena { get; set; }
        public Nullable<bool> Admin { get; set; }
    
        public virtual ICollection<Aukcija> Aukcijas { get; set; }
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual ICollection<Narudzbina> Narudzbinas { get; set; }
    }
}
