//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veb_portal_za_aukcijsku_prodaju.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbina
    {
        public int NarudzbinaID { get; set; }
        public Nullable<decimal> CenaTokena { get; set; }
        public string Status { get; set; }
        public Nullable<int> BrojTokena { get; set; }
        public Nullable<System.DateTime> DatumPravljenja { get; set; }
        public Nullable<int> KorisnikID { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
